apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-nginx-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: first-nginx-container
          image: nginx:latest
